### ISSUE TITLE
Strange errors after Update to 3.5

### ISSUE THREAD

**Issue by HumanBot000** [KeeganMartin/ArduinoDictionary#5]
I just updated the libary to 3.5 and now nothing works anymore. The bad thing is, I don't know which version I had before.

```
#include <Dictionary.h>
Dictionary<int, String> screen_content_dict;
for (int i = 0; i < num_displays; i++) {
    screen_content_dict.set(i, "-1");}
if (current_display_content == screen_content_dict.get(current_display_updating) && current_display_updating != 3)
```

```
 error: 'Dictionary' is not a template
 Dictionary<int, String> screen_content_dict;
 ^~~~~~~~~~
error: 'class Dictionary' has no member named 'set'
     screen_content_dict.set(i, "-1");
                         ^~~
error: 'class Dictionary' has no member named 'get'
   if (current_display_content == screen_content_dict.get(current_display_updating) && current_display_updating != 3) {
                                                      ^~~
error: 'class Dictionary' has no member named 'set'
   screen_content_dict.set(current_display_updating, current_display_content);
                       ^~~
 ```
